site_name: 粼光开放平台
theme:
  name: material
  logo: https://lgboxs.com/icons/safari-pinned-tab.svg
  favicon: https://lgboxs.com/icons/safari-pinned-tab.svg
  language: zh
  features:
    - navigation.instant
    - toc.integrate
    - content.code.copy
    - navigation.top
    - navigation.instant.progress
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  generator: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/SparklingSt/docs
site_url: https://sparklingst.github.io/docs
